# 不同的环境使用不同的配置
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
# 测试环境：java -jar xxx.jar --spring.profiles.active=test
# 生产环境：java -jar xxx.jar --spring.profiles.active=prod
spring: 
  profiles: 
    active: dev
  datasource: 
    # mysql
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 连接池
    maximum-pool-size: 50
    max-idle: 10
    max-wait: 5000
    min-idle: 10
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true
    
  jackson: 
    serialization:
      indent_output: true
      
  redis: # redis
    database: 1
    host: 127.0.0.1
    password:   
    port: 6379
    pool:
      max-idle: 8
      min-idle: 1
      max-active: 8
      max-wait: -1
      #sentinel: 
        #master=  
      #sentinel:
        #nodes=  
    timeout: 60000

# tomcat
server:
  port: 8080

#自定义属性
name: zhangsan
age: 30
address: hanzhou
remark: my name is ${name}

# mybatis
mybatis: 
  config-location: classpath:mybatis-config.xml
  
#下面这一行务必不能少，区分不同配置，而且必须是三个字符"-"
---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.0.152:3306/aylson?useUnicode=true&characterEncoding=UTF-8&useSSL=false

---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.0.152:13306/aylson?useUnicode=true&characterEncoding=UTF-8&useSSL=false

---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.152:23306/aylson?useUnicode=true&characterEncoding=UTF-8&useSSL=false